index:
  path: /
  controller: App\Controller\DefaultController::index

OrderDelivery:
  # loads routes from the YAML or XML files found in some bundle directory
  resource: "../src/OrderDelivery/Infrastructure/Config/routing/"
  type: directory
