App\OrderDelivery\Domain\ValueObject\OrderType:
    type: entity
    table: order_type
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
    fields:
        name:
            type: string
            length: 30